/*
* 本文件内容不要人为修改，本文件由"python3 Christmas.py Input/MergeCode/LinkModule"生成
* 如果再次运行生成脚本，人为修改的代码将被删除
* 
* The contents of this file should not be modified. This file is generated by "python3 Christmas.py Input/MergeCode/LinkModule"
* If the generation script is run again, the artificially modified code will be deleted
*/

#ifndef   _COMMON_CONFIG_HPP_
#define   _COMMON_CONFIG_HPP_

    //Common
    #define CONFIG_All_DEBUG true
    #define CONFIG_All_Version "2.0=@@date@@"
    #define CONFIG_All_Logger_Root "./log/"
    //_BrokerLogger
    //_DataQueue
    //_DataFilling
    //_DataCheck
    //_BrokerCall
    //_ServerHttp
    #define CONFIG__ServerHttp_TimeoutConnect 10
    #define CONFIG__ServerHttp_TimeoutRead 5
    #define CONFIG__ServerHttp_TimeoutWrite 5
    //_BrokerThread

#endif