/*
* 本文件内容不要人为修改，本文件由"python3 Christmas.py Input/MergeCode/LinkModule"生成
* 如果再次运行生成脚本，人为修改的代码将被删除
* 
* The contents of this file should not be modified. This file is generated by "python3 Christmas.py Input/MergeCode/LinkModule"
* If the generation script is run again, the artificially modified code will be deleted
*/

#ifndef   _Module_HPP_
#define   _Module_HPP_

#include "Kernel/Common/Common.hpp"
#include "Kernel/Module/Link.hpp"
#include <string>
#include <map>

#include "Kernel/Module/_BrokerLogger/_BrokerLogger.hpp"
#include "Kernel/Module/_DataQueue/_DataQueue.hpp"
#include "Kernel/Module/_DataFilling/_DataFilling.hpp"
#include "Kernel/Module/_DataCheck/_DataCheck.hpp"
#include "Kernel/Module/_BrokerCall/_BrokerCall.hpp"
#include "Kernel/Module/_ServerHttp/_ServerHttp.hpp"
#include "Kernel/Module/_BrokerThread/_BrokerThread.hpp"

#define START_MODULE(module, moduleParam, passParam) Module::ModuleCall(module, moduleParam, passParam)

namespace Module{
    std::map<std::string, Module::Link*> moduleMap = {
    {"_BrokerLogger", new _BrokerLogger()},
    {"_DataQueue", new _DataQueue()},
    {"_DataFilling", new _DataFilling()},
    {"_DataCheck", new _DataCheck()},
    {"_BrokerCall", new _BrokerCall()},
    {"_ServerHttp", new _ServerHttp()},
    {"_BrokerThread", new _BrokerThread()},
    };

    ERROR_CODE ModuleCall(std::string module, Json::Value& moduleParam, Json::Value& passParam){
        if(Module::moduleMap.count(module)) {
            LOGGER_LocateAdd("M-"+module);
            ERROR_CODE ret = (Module::moduleMap[module])->Start(moduleParam, passParam);
            LOGGER_LocateDelete();
            return ret;
        }else{
            LOGGER_Error("Module Lack:"+module, moduleParam, passParam);
            return ERR_ModuleLack;
        }
    };
}

#endif