//此文件由Christmas根据xxx.json生成，请不要手动修改
//This file is generated by Christmas according to xxx.json. Please do not modify it manually
#ifndef   _TASK_Start_HPP_
#define   _TASK_Start_HPP_

#include "Kernel/Common/Common.hpp"
#include "Kernel/Module/Module.hpp"
#include <unistd.h>

namespace Task{
    namespace Start{
        ERROR_CODE Start(Json::Value &passParam){
            //STEP::Init data
            Json::Value moduleParam = Json::objectValue;
            ERROR_CODE ret = ERR_OK;
            Json::Reader reader;
            std::vector<std::pair<int, Json::Value>> selectorRetryData;
            LOGGER_Info("Task function Start start", moduleParam, passParam);
        
            //STEP::Run module
            do{
                //STEP::Call _DataQueue
                reader.parse(R"({"_action": "create", "_identity": "Start>>Data", "_queueMaxLen": 1})", moduleParam);
                ret = START_MODULE("_DataQueue", moduleParam, passParam);
                if(ERRORCODE_IsError(ret, {
                   
                })){
                    LOGGER_Error("Task interrupt! errorCode:"+ERRORCODE_GetCode(ret)+" ,message:"+ERRORCODE_GetMessage(ret), moduleParam, passParam);
                    continue;
                }
                TOOLS_JsonClean(moduleParam);
                
                //STEP::Call _BrokerThread
                reader.parse(R"({"_action": "create", "_identity": "Start>>SamplePush", "_call": "SamplePush"})", moduleParam);
                ret = START_MODULE("_BrokerThread", moduleParam, passParam);
                if(ERRORCODE_IsError(ret, {
                   
                })){
                    LOGGER_Error("Task interrupt! errorCode:"+ERRORCODE_GetCode(ret)+" ,message:"+ERRORCODE_GetMessage(ret), moduleParam, passParam);
                    continue;
                }
                TOOLS_JsonClean(moduleParam);
                
                //STEP::Call _BrokerThread
                reader.parse(R"({"_action": "create", "_identity": "Start>>SampleGet", "_call": "SampleGet"})", moduleParam);
                ret = START_MODULE("_BrokerThread", moduleParam, passParam);
                if(ERRORCODE_IsError(ret, {
                   
                })){
                    LOGGER_Error("Task interrupt! errorCode:"+ERRORCODE_GetCode(ret)+" ,message:"+ERRORCODE_GetMessage(ret), moduleParam, passParam);
                    continue;
                }
                TOOLS_JsonClean(moduleParam);
                
                //STEP::Call _BrokerThread
                reader.parse(R"({"_action": "wait all"})", moduleParam);
                ret = START_MODULE("_BrokerThread", moduleParam, passParam);
                if(ERRORCODE_IsError(ret, {
                   
                })){
                    LOGGER_Error("Task interrupt! errorCode:"+ERRORCODE_GetCode(ret)+" ,message:"+ERRORCODE_GetMessage(ret), moduleParam, passParam);
                    continue;
                }
                TOOLS_JsonClean(moduleParam);
                
                //STEP::Call _DataQueue
                reader.parse(R"({"_action": "delete", "_identity": "Start>>Data"})", moduleParam);
                ret = START_MODULE("_DataQueue", moduleParam, passParam);
                if(ERRORCODE_IsError(ret, {
                   
                })){
                    LOGGER_Error("Task interrupt! errorCode:"+ERRORCODE_GetCode(ret)+" ,message:"+ERRORCODE_GetMessage(ret), moduleParam, passParam);
                    continue;
                }
                TOOLS_JsonClean(moduleParam);
                
            }while(false);
            LOGGER_Info("Task function Start end", moduleParam, passParam);
            return ret;
        };
        
    }
}

#endif